# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  format:
    cmds:
      - go tool gofumpt -l -w .

  lint:
    cmds:
      - go tool golangci-lint run --fix ./...

  test:
    cmds:
      - go test ./...

  test:clean:
    cmds:
      - go clean -testcache
      - task: test

  run:services:
    cmds:
      - docker compose up -d
